title: Cesar's Ramirez CIT_481 Blog 3_2022

logo: /assets/img/lambda.jpg
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
